name: jira_add_on
description: Command-line tool to log working hours on Jira.
version: 0.2.0

environment:
  sdk: ^3.4.1

dependencies:
  args: ^2.5.0
  deep_pick: ^1.0.0
  dio: ^5.5.0+1
  dotenv: ^4.2.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

executables:
  jira_add_on:
